### ISSUE TITLE
Ревью ДЗ 3

### ISSUE THREAD

**Issue by blaackpanter** [magellon17/vk-testing-tasks#10]
Хорошая работа!

**login(String email, String password)**
1. Лучше разнести на ввести логин, ввести пароль, нажать кнопки залогиниться. Мы можем захотеть потестить ввести логин + клик кнопку войти, ввести пароль + нажать кнопку войти

$(profileAvatar).shouldBe(visible.because(PROFILE_AVATAR_LOG_INFO));
2. Вот тут интересный случай. Текст because и в ассертах лучше не выносить в константу, а оставить прямо тут. Лучше читается код, особенно, когда пейдж длинный. В deleteLastTextPost() правильно.

3. А вот такое в константу в начало класса GroupPage groupPage = groupsPage.createGroup(**"myGroup"**);
**String newUserName = "Boris";**

5. В константу $(byXpath(".//*[text()='Удалить заметку']"))

```
**public FeedPage() {
        checkPage();
    }**
```
6. Надо бы сделать так, чтобы всем потомкам BaseMainPage (потомкам BasePage) приходилось делать эту проверку. Нужно подумать через @ Override.

 Selenide.refresh();
7. После рефрена всегда новый экземпляр класса должен создаваться. Страница вообще могла не загрузиться.

8. Не увидела дополнительных аннотаций junit.

По всем вопросам можно писать в ВК.

**Comment by magellon17** [comment]
@blaackpanter Спасибо за фидбек ! Есть вопрос по 6 пункту ревью. А зачем всем потомкам BaseMainPage делать проверку FeedPage ? Они ее не пройдут просто.

**Comment by magellon17** [comment]
У меня идея была в том, чтобы, например, в GroupPage была такая логика проверок BasePage -> BaseMainPage -> GroupPage. То есть 3 проверки. То есть я проверяю, что страница корректно открылась. Вместе с общими элементами(например, меню навигации)
Может GroupPage и открылся, но на нем мог не открыться важный элемент BaseMainPage. Поэтому я не переопределял checkPage().

**Comment by blaackpanter** [comment]
Добрый вечер! Идея была в том, чтобы каждый класс имел свой check(), у него были какие-то проверки. Может и проверяться что-то в классе родителя, это ок.

**Comment by magellon17** [comment]
@blaackpanter Еще хотел спросить, есть ли какой-то общедоступный проект UI автотестов, на который можно ориентироваться как на хороший референс ?
